// generated by `sqlx migrate build-script`
fn main() {
  // cargo へのbuild指示 cargo build でこれを見る
  // migrations配下が変更さた場合、本体を再コンパイル 新しいSQLをバイナリに埋め込み、サーバ起動時にDBに適用
  // trigger recompilation when a new migration is added
  println!("cargo:rerun-if-changed=migrations");
}
