services:
  # タスク管理用キュー (Redis)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save 60 1
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ファイル共有ストレージ (MinIO)
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000" # API用ポート
      - "9001:9001" # Web管理コンソール用ポート
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # MINIO デフォルトでバケット作成
  create_buckets:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    # 30秒待っても接続できなかったらエラー
    # set -e: エラーが発生したらスクリプトを終了
    # $(seq 1 30);: 1から30までの数列を生成
    # --ignore-existing: 既にバケットが存在してても良い
    entrypoint: >
      /bin/sh -c "
      set -e;
      for i in $(seq 1 30); do
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && break;
        sleep 1;
      done;
      mc mb --ignore-existing local/${MINIO_BUCKET_NAME};
      exit 0;
      "
    networks:
      - default

  # 実行結果・メタデータ管理用 (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: # DBのデータ領域。NASに置くとI/O遅延で壊れる可能性があるためVMのローカルに作成
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s


  frontend:
    init: true  # ゾンビプロセスを防ぐ
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - default


  backend:
    init: true  # ゾンビプロセスを防ぐ
    environment:
      - TZ=Asia/Tokyo
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      db:
        condition: service_healthy  # DBのヘルスチェック待機
      redis:
        condition: service_healthy # Redisのヘルスチェック待機
      minio:
        condition: service_healthy # MinIOのヘルスチェック待機
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/tasks"]
      interval: 5s
      timeout: 3s
      retries: 6
      start_period: 30s



volumes:
  redis_data:
  db_data:
