services:
  backend:
    image: orchestrator-backend:dev
    pull_policy: never
    working_dir: /app
    user: "${UID:-1000}:${GID:-1000}" # キャッシュをユーザーに紐づける
    volumes:
      - ./backend:/app
      - ../schema:/schema          # OpenAPIスキーマをマウント
      - ./.ci-cache/cargo-target:/app/target # ターゲット
      - ./.ci-cache/cargo-registry:/usr/local/cargo/registry # 依存キャッシュ

  frontend: !reset null # 使用しないサービスを削除