services:
  backend:
    image: orchestrator-backend:dev
    pull_policy: never
    working_dir: /app
    volumes:
      - ./backend:/app
      - ../schema:/schema          # OpenAPIスキーマをマウント

  frontend: !reset null # 使用しないサービスを削除