services:
  redis:
    profiles: ["infra"]

  minio:
    # init時にcreate_bucketsのdepends_onが見えるように、initプロファイルも指定
    profiles: ["infra", "init"]
    # NASをマウントしたディレクトリをMinIOの保存領域として指定
    volumes:
      - /mnt/kslib/minio_data:/data

  db:
    profiles: ["infra"]
  create_buckets:
    profiles: ["init"]

  # frontendとbackendはデプロイで来るので行わない
  frontend:
    profiles: ["app"]
  backend:
    profiles: ["app"]