services:
  # タスク管理用キュー (Redis)
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # ファイル共有ストレージ (MinIO)
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000" # API用ポート
      - "9001:9001" # Web管理コンソール用ポート
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    # kslibをマウントしたディレクトリをMinIOの保存領域として指定
    volumes:
      - /mnt/kslib/minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  # 実行結果・メタデータ管理用 (PostgreSQL)
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes: # DBのデータ領域。NASに置くとI/O遅延で壊れる可能性があるためVMのローカルに作成
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 10s


  frontend:
    init: true  # ゾンビプロセスを防ぐ
    restart: unless-stopped
    build:
      context: ./frontend   # ./frontend の Dockerfile を使用
      target: dev  # ビルドステージ指定
    # restart: unless-stopped は設けない: エラーログを残す、chargo watch でのホットリロードとの競合を避ける
    environment:
      - APP_ENV=dev                 # アプリ側で開発モードを認識させる
      - CHOKIDAR_USEPOLLING=true    # ファイル変更検知を確実にする
    volumes:
      - ./frontend:/app             # ホストのソースコードを同期
      - /app/node_modules           # コンテナ内の依存関係を守る(ホスト側で上書きしない)
    ports:
      - "80:80"
    depends_on:
      - backend


  backend:
    init: true  # ゾンビプロセスを防ぐ
    restart: unless-stopped
    build:
      context: ./backend  # ./backend の Dockerfile を使用
      target: dev
    working_dir: /app
    environment:
      - TZ=Asia/Tokyo
      - APP_ENV=dev
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - REDIS_URL=${REDIS_URL}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
      - MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
    depends_on:
      db:
        condition: service_healthy  # DBのヘルスチェック待機
      redis:
        condition: service_healthy # Redisのヘルスチェック待機
      minio:
        condition: service_healthy # MinIOのヘルスチェック待機
    volumes:
      - ./backend:/app
      - target_cache:/app/target # ビルドキャッシュを永続化して、ビルド時間短縮、 cargo watch競合回避
      - cargo_cache:/usr/local/cargo/registry # Cargoの依存キャッシュも永続化
    ports:
      - "3000:3000"
    networks:
      - default



volumes:
  redis_data:
  db_data:
  target_cache:
  cargo_cache: