/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 実験の一覧取得 */
        get: operations["get_all_experiments"];
        /** 実験の結果反映 */
        put: operations["reflect_experiment_results"];
        /** 実験の作成 */
        post: operations["create_experiment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 処理取得の報告 */
        put: operations["claim_experiment"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 実験の削除
         *     Path: /experiments/{id} のような指定の場合 idを取ってこれるエクストラクタ
         */
        delete: operations["delete_experiment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/files/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ファイルの取得 */
        get: operations["get_file"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** タスクの一覧取得 */
        get: operations["get_all_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** タスクの削除 */
        delete: operations["delete_task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 処理取得の報告リクエスト */
        ClaimExperimentRequest: {
            /**
             * Format: int64
             * @description 実験ID
             */
            id: number;
            /** @description ワーカー名 */
            worker_name: string;
        };
        /** @description 実験の作成リクエスト */
        CreateExperimentRequest: {
            /**
             * Format: int64
             * @description 既存実験結果を流用する実験結果
             * @default null
             */
            base_experiment_id: number | null;
            /**
             * Format: int32
             * @description バッチサイズ
             * @default 256
             */
            batch_size: number;
            /** @description その他のハイパーパラメータ */
            hyperparameters?: Record<string, never>;
            /**
             * @description 攻撃モデルを読み込むかどうか
             * @default false
             */
            load_attack_model: boolean;
            /**
             * @description シャドウモデルを読み込むかどうか
             * @default false
             */
            load_shadow_model: boolean;
            /**
             * @description ターゲットモデルを読み込むかどうか
             * @default false
             */
            load_target_model: boolean;
            /**
             * Format: int32
             * @description 最大エポック数
             * @default 200
             */
            max_epochs: number;
            /** @default OfflineLira */
            method: components["schemas"]["MiaMethod"];
            /**
             * @description 実験名
             * @default 2026-05-17_08-42-55
             */
            name: string;
            /**
             * @description 備考
             * @default null
             */
            notes: string | null;
            /**
             * Format: int32
             * @description シャドウモデル数
             * @default 100
             */
            num_shadow_models: number;
            /**
             * Format: int32
             * @description シード値
             * @default 42
             */
            seed: number;
            /**
             * Format: int32
             * @description シャドウモデルのテストサイズ
             * @default 10520
             */
            shadow_test_size: number;
            /**
             * Format: int32
             * @description シャドウモデルのトレーニングサイズ
             * @default 10520
             */
            shadow_train_size: number;
            /**
             * Format: int32
             * @description ターゲットモデルのテストサイズ
             * @default 10520
             */
            target_test_size: number;
            /**
             * Format: int32
             * @description ターゲットモデルのトレーニングサイズ
             * @default 10520
             */
            target_train_size: number;
        };
        /** @enum {string} */
        ExperimentStatus: "Waiting" | "Running" | "Succeeded" | "Failed";
        /** @enum {string} */
        MiaMethod: "OfflineLira" | "Shokri";
        Model: {
            /**
             * Format: int64
             * @description 既存実験結果を流用する実験結果
             */
            base_experiment_id?: number | null;
            /**
             * Format: int32
             * @description バッチサイズ
             */
            batch_size: number;
            /**
             * Format: date-time
             * @description 完了日時
             */
            completed_at?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            created_at: string;
            /** @description エラーメッセージ */
            error_message?: string | null;
            files?: Record<string, never> | null;
            /**
             * Format: double
             * @description 全体のAUC
             */
            global_auc?: number | null;
            /** @description その他のハイパーパラメータ */
            hyperparameters: Record<string, never>;
            /**
             * Format: int64
             * @description 主キー
             */
            id: number;
            /** @description 攻撃モデルを読み込むかどうか */
            load_attack_model: boolean;
            /** @description シャドウモデルを読み込むかどうか */
            load_shadow_model: boolean;
            /** @description ターゲットモデルを読み込むかどうか */
            load_target_model: boolean;
            /**
             * Format: int32
             * @description 最大エポック数
             */
            max_epochs: number;
            /** @description 攻撃手法 */
            method: components["schemas"]["MiaMethod"];
            /** @description 実験名 */
            name: string;
            /** @description 備考 */
            notes?: string | null;
            /**
             * Format: int32
             * @description シャドウモデル数
             */
            num_shadow_models: number;
            /** @description その他のメトリクス */
            other_metrics?: Record<string, never> | null;
            /**
             * Format: int32
             * @description シード値
             */
            seed: number;
            /**
             * Format: int32
             * @description シャドウモデルのテストサイズ
             */
            shadow_test_size: number;
            /**
             * Format: int32
             * @description シャドウモデルのトレーニングサイズ
             */
            shadow_train_size: number;
            /** @description ステータス */
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Format: int32
             * @description ターゲットモデルのテストサイズ
             */
            target_test_size: number;
            /**
             * Format: int32
             * @description ターゲットモデルのトレーニングサイズ
             */
            target_train_size: number;
            /**
             * Format: double
             * @description 0.1%FPRでの閾値
             */
            threshold_at_01_fpr?: number | null;
            /**
             * Format: double
             * @description 1%FPRでの閾値
             */
            threshold_at_1_fpr?: number | null;
            /**
             * Format: double
             * @description トータルの実行時間(秒)
             */
            total_time?: number | null;
            /**
             * Format: double
             * @description 0.1%FPRでのTPR
             */
            tpr_at_01_fpr?: number | null;
            /**
             * Format: double
             * @description 1%FPRでのTPR
             */
            tpr_at_1_fpr?: number | null;
            /** @description 作業PC名 */
            worker_name?: string | null;
        };
        /** @description タスク */
        Task: {
            /** @description 制御情報 */
            args_control: Record<string, never>;
            /** @description キーワード引数 */
            args_keyword: Record<string, never>;
            /** @description 位置引数 */
            args_positional: Record<string, never>;
            /** @description エラーメッセージ */
            error_message?: string | null;
            /**
             * Format: int64
             * @description 実験ID
             */
            experiment_id: number;
            /**
             * Format: uuid
             * @description id
             */
            id: string;
            /** @description タスク名 */
            task: string;
        };
        /** @description 実験の結果更新リクエスト */
        UpdateResultsRequest: {
            /** @description エラーメッセージ */
            error_message?: string | null;
            /**
             * Format: int64
             * @description 実験ID
             */
            experiment_id: number;
            /** @description その他のファイルのパス */
            files: Record<string, never>;
            /**
             * Format: double
             * @description 全体のAUC
             */
            global_auc?: number | null;
            /** @description 拡張メトリクス */
            other_metrics: Record<string, never>;
            /** @description 実験結果 ステータス */
            status: components["schemas"]["ExperimentStatus"];
            /**
             * Format: double
             * @description 0.1%FPRでの閾値
             */
            threshold_at_01_fpr?: number | null;
            /**
             * Format: double
             * @description 1%FPRでの閾値
             */
            threshold_at_1_fpr?: number | null;
            /**
             * Format: double
             * @description トータルの実行時間(秒)
             */
            total_time?: number | null;
            /**
             * Format: double
             * @description 0.1%FPRでのTPR
             */
            tpr_at_01_fpr?: number | null;
            /**
             * Format: double
             * @description 1%FPRでのTPR
             */
            tpr_at_1_fpr?: number | null;
            /** @description 作業PC名 */
            worker_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_all_experiments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 実験の一覧を取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"][];
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reflect_experiment_results: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateResultsRequest"];
            };
        };
        responses: {
            /** @description 実験結果が正常に反映された */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description 指定された実験が見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExperimentRequest"];
            };
        };
        responses: {
            /** @description 実験が正常に作成された */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    claim_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimExperimentRequest"];
            };
        };
        responses: {
            /** @description 処理取得が正常に報告された */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Model"];
                };
            };
            /** @description 指定された実験が見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_experiment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 削除する実験のID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 実験が正常に削除された */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": number;
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ファイルが正常に取得された */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": number[];
                };
            };
            /** @description ファイルが見つからない */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_all_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description タスクの一覧を取得 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 削除するタスクのID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description タスクが正常に削除された */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": number;
                };
            };
            /** @description サーバー内部エラー */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
