server {
	# デフォルトサーバーに設定: server_nameが一致するものがない場合にこのサーバーが使われる
	listen 80 default_server;

	root /usr/share/nginx/html;
	index index.html;

	# 後でCSPに変更する
	# クリックジャッキング対策
	add_header X-Frame-Options "SAMEORIGIN";
	# MIMEタイプスニフィング対策
	add_header X-Content-Type-Options "nosniff";
	# XSSフィルター有効化
	add_header X-XSS-Protection "1; mode=block";

	# フロントエンド (SPA) のための設定
	# 存在しないパスへのアクセスは index.html にフォールバックさせる
	location / {
		try_files $uri $uri/ /index.html;
	}

	# APIリクエストをRustバックエンドへ転送
	# http://backend:3000 は Docker Compose のサービス名で解決される
	location /api/ {
		# APIリクエストをバックエンドにプロキシ: 末尾に / があると /api/endpoint が /endpoint に変換される(良くない)
		proxy_pass http://backend:3000;
		
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}

	# Swagger UI のための設定
	location /docs/ {
		proxy_pass http://backend:3000;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}