services:
  ito_research:
    restart: unless-stopped
    image: ${REGISTRY:-ghcr.io}/${IMAGE_PREFIX}/worker@${WORKER_DIGEST}
    pull_policy: always

    # タスク保護 実行中のタスクが完了してから終了: 16時間まで待つ
    # SIGTERMが送信されてから、SIGKILLが送信されるまでの時間
    # CeleryはSIGTERMを受け取ると、タスクを完了させて終了させる
    stop_grace_period: 1h
    volumes:
      - miaos_worker_data:/workspace/data # データセット
      - miaos_worker_cache:/workspace/cache # キャッシュ(他の実験結果など)

volumes:
  miaos_worker_data:
  miaos_worker_cache:
