services:
  ito_research:
    build:
      context: .
      target: dev
    stdin_open: true  # 標準入力を開放
    tty: true  # ターミナル割り当て

    volumes:
      - ./:/workspace
      - /workspace/.venv  # 匿名ボリューム ホストの.venvで上書きしない
      - ../schema:/schema:ro  # OpenAPIスキーマをマウント
    # ヘルスチェックを無効化
    healthcheck:
      disable: true
